motorcmd: 
 -
  info:
    position: FL_hip
    id: 0
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 0
    W: 0.0
    T: 0.0
 -
  info:
    position: FL_thigh
    id: 1
    mode: 1
    K_P: 180
    K_W: 50    
    Pos: 0
    W: 0.0
    T: 0.0
 -
  info:
    position: FL_calf
    id: 2
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 0
    W: 0.0
    T: 0.0
 -
  info:
    position: RL_hip
    id: 3
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 0.006 
    W: 0.0
    T: 0.0
 -
  info:
    position: RL_thigh
    id: 4
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 0.567
    W: 0.0
    T: 0.0
 -
  info:
    position: RL_calf
    id: 5
    mode: 1
    K_P: 180
    K_W: 50
    Pos: -1.672
    W: 0.0
    T: 0.0
 -
  info:
    position: FR_hip
    id: 6
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 0.0758
    W: 0.0
    T: 0.0
 -
  info:
    position: FR_thigh
    id: 7
    mode: 1
    K_P: 180
    K_W: 50
    Pos: -0.517
    W: 0.0
    T: 0.0
 -
  info:
    position: FR_calf
    id: 8
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 1.559
    W: 0.0
    T: 0.0
 -
  info:
    position: RR_hip
    id: 9
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 0.021
    W: 0.0
    T: 0.0
 -
  info:
    position: RR_thigh
    id: 10
    mode: 1
    K_P: 180
    K_W: 50
    Pos: -0.700
    W: 0.0
    T: 0.0
 -
  info:
    position: RR_calf
    id: 11
    mode: 1
    K_P: 180
    K_W: 50
    Pos: 1.564
    W: 0.0
    T: 0.0